experiment:
  name: llama32_1b
  output_dir: outputs/llama32_1b_cl
  results_dir: results/llama32_1b_cl
  num_epochs: 1
  seed: [33]

model:
  name: meta-llama/Llama-3.2-1B-Instruct
  trust_remote_code: true
  torch_dtype: auto

continual_learning:
  task_order:
    - task_1
    - task_2
    - task_3

tasks:
  task_1:
    name: fomc
    train_file: data/llm-cl-500/FOMC/train.json
    val_file: data/llm-cl-500/FOMC/eval.json
    test_file: data/llm-cl-500/FOMC/test.json

  task_2:
    name: scienceqa
    train_file: data/llm-cl-500/ScienceQA/train.json
    val_file: data/llm-cl-500/ScienceQA/eval.json
    test_file: data/llm-cl-500/ScienceQA/test.json

  task_3:
    name: numgluecm
    train_file: data/llm-cl-500/NumGLUE-cm/train.json
    val_file: data/llm-cl-500/NumGLUE-cm/eval.json
    test_file: data/llm-cl-500/NumGLUE-cm/test.json
