experiment:
  name: qwen35_08b
  output_dir: outputs/qwen35_08b_cl
  results_dir: results/qwen35_08b_cl
  seed: [33]

training:
  num_epochs: 1
  batch_size: 1
  gradient_accumulation_steps: 4
  learning_rate: 5e-5
  max_length: 512
  # max_train_batches: 5

evaluation:
  max_new_tokens: 256

model:
  name: Qwen/Qwen3.5-0.8B
  trust_remote_code: true
  torch_dtype: auto

continual_learning:
  task_order:
    - task_1
    - task_2
    - task_3

tasks:
  task_1:
    name: fomc
    train_file: data/llm-cl-500/FOMC/train.json
    val_file: data/llm-cl-500/FOMC/eval.json
    test_file: data/llm-cl-500/FOMC/test.json

  task_2:
    name: scienceqa
    train_file: data/llm-cl-500/ScienceQA/train.json
    val_file: data/llm-cl-500/ScienceQA/eval.json
    test_file: data/llm-cl-500/ScienceQA/test.json

  task_3:
    name: numgluecm
    train_file: data/llm-cl-500/NumGLUE-cm/train.json
    val_file: data/llm-cl-500/NumGLUE-cm/eval.json
    test_file: data/llm-cl-500/NumGLUE-cm/test.json
